spring.application.name=retail-ai-assistant

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:retail_ai}
spring.datasource.username=${DB_USER:retail}
spring.datasource.password=${DB_PASSWORD:retail}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

spring.ai.openai.base-url=${OPENAI_BASE_URL:}
spring.ai.openai.api-key=${OPENAI_API_KEY:}
spring.ai.openai.chat.options.model=model=${OPENAI_CHAT_MODEL:openai.gpt-5-mini}
spring.ai.openai.chat.options.temperature=0.2


custom.embedding.url=${OPENAI_BASE_URL:}
custom.embedding.api-key=${OPENAI_API_KEY:}
custom.embedding.model=${OPENAI_EMBEDDING_MODEL:}
custom.embedding.dimensions=${CUSTOM_EMBEDDING_DIMENSIONS:1536}

spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.index-type=HNSW
spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE
spring.ai.vectorstore.pgvector.dimensions=1536

spring.web.resources.cache.period=0

management.endpoints.web.exposure.include=health,info,metrics

logging.level.com.example.retailai=INFO
logging.level.org.springframework.ai=INFO

logging.level.org.springframework.ai.openai=DEBUG
logging.level.org.springframework.web.reactive.function.client=DEBUG

server.port=8080